export const textureEnum = {
  shipBlue: 'shipBlue',
  shipBlue2: 'shipBlue2',
  bomb: 'bomb',
  musicOn: 'musicOn',
  musicOff: 'musicOff',
  effectsOn: 'effectsOn',
  effectsOff: 'effectsOff',
  enemyShip: 'enemyShip',
  man: 'man',
  man2: 'man2',
  woman: 'woman',
  TombStone1: 'TombStone1',
  TombStone2: 'TombStone2',
  spaceShip: 'spaceShip',
  bullet1: 'bullet1',
  bullet2: 'bullet2',
  explosion: 'explosion',
  explosion1: 'explosion1',
  explosion2: 'explosion2',
  explosion3: 'explosion3',
};

export const allTextures = {
  shipBlue: 'assets/sprites/enemy/shipBlue.png',
  shipBlue2: 'assets/sprites/enemy/shipBlue2.png',
  bomb: 'assets/sprites/bomb.png',
  musicOn: 'assets/sprites/ui/music_on.png',
  musicOff: 'assets/sprites/ui/music_off.png',
  effectsOn: 'assets/sprites/ui/volume_on.png',
  effectsOff: 'assets/sprites/ui/volume_off.png',
  enemyShip: 'assets/sprites/enemy/shipBlue.png',
  man: 'assets/sprites/people/man.png',
  man2: 'assets/sprites/people/man2.png',
  woman: 'assets/sprites/people/woman.png',
  TombStone1: 'assets/sprites/people/TombStone1.png',
  TombStone2: 'assets/sprites/people/TombStone2.png',
  spaceShip: 'assets/sprites/player.png',
  bullet1: 'assets/sprites/bullets/bullet1.json',
  bullet2: 'assets/sprites/bullets/bullet2.json',
  explosion: 'assets/sprites/explosion/explosion.json',
  explosion1: 'assets/sprites/explosion/explosion1.json',
  explosion2: 'assets/sprites/explosion/explosion2.json',
  explosion3: 'assets/sprites/explosion/explosion3.json',
};
